In [1]:
from Univariate import univariate

In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv("Placement.csv")

In [4]:
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

In [5]:
quan,qual=univariate.quanQual(dataset)

In [6]:
quan,qual

(['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

In [7]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [8]:
qual

['gender',
 'ssc_b',
 'hsc_b',
 'hsc_s',
 'degree_t',
 'workex',
 'specialisation',
 'status']

In [9]:
columnName=dataset.columns

In [10]:
columnName

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='str')

In [11]:
freq=univariate.freqTable(columnName,dataset)

In [12]:
freq

    Unique_Values  Frequency  Relative Frequency     Cusum
0        300000.0         22            0.213592  0.213592
1        250000.0         18            0.174757  0.388350
2        240000.0         15            0.145631  0.533981
3        260000.0          7            0.067961  0.601942
4        200000.0          6            0.058252  0.660194
5        265000.0          6            0.058252  0.718447
6        360000.0          6            0.058252  0.776699
7        220000.0          5            0.048544  0.825243
8        275000.0          5            0.048544  0.873786
9        270000.0          4            0.038835  0.912621
10       400000.0          4            0.038835  0.951456
11       210000.0          4            0.038835  0.990291
12       350000.0          3            0.029126  1.019417
13       216000.0          3            0.029126  1.048544
14       500000.0          3            0.029126  1.077670
15       252000.0          2            0.019417  1.097087
16       218000.0          2            0.019417  1.116505
17       236000.0          2            0.019417  1.135922
18       204000.0          2            0.019417  1.155340
19       230000.0          2            0.019417  1.174757
20       280000.0          2            0.019417  1.194175
21       276000.0          2            0.019417  1.213592
22       425000.0          1            0.009709  1.223301
23       231000.0          1            0.009709  1.233010
24       393000.0          1            0.009709  1.242718
25       278000.0          1            0.009709  1.252427
26       320000.0          1            0.009709  1.262136
27       411000.0          1            0.009709  1.271845
28       287000.0          1            0.009709  1.281553
29       450000.0          1            0.009709  1.291262
30       268000.0          1            0.009709  1.300971
31       336000.0          1            0.009709  1.310680
32       420000.0          1            0.009709  1.320388
33       380000.0          1            0.009709  1.330097
34       940000.0          1            0.009709  1.339806
35       225000.0          1            0.009709  1.349515
36       233000.0          1            0.009709  1.359223
37       690000.0          1            0.009709  1.368932
38       340000.0          1            0.009709  1.378641
39       255000.0          1            0.009709  1.388350
40       285000.0          1            0.009709  1.398058
41       290000.0          1            0.009709  1.407767
42       650000.0          1            0.009709  1.417476
43       264000.0          1            0.009709  1.427184
44       295000.0          1            0.009709  1.436893

In [13]:
descriptive=univariate.Univariate(dataset,quan)

In [14]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max,215,89.4,97.7,91.0,98.0,77.89,940000.0
kurtosis,-1.2,-0.60751,0.450765,0.052143,-1.08858,-0.470723,18.544273
skew,0.0,-0.132649,0.163639,0.244917,0.282308,0.313576,3.569747
Var,3870.0,117.228377,118.755706,54.151103,176.251018,34.028376,8734295412.759695
Std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.45242