In [68]:
import pandas as pd
import numpy as py 
import matplotlib.pyplot as plt

In [69]:
dataset=pd.read_csv("CKD.csv")

In [70]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [71]:
dataset["classification"].value_counts()

classification
yes    249
no     150
Name: count, dtype: int64

In [72]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [73]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [55]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [74]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes',]]

In [75]:
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2,76,3,0,148,57,3,137,4,12,...,1,0,0,0,0,0,0,1,1,0
1,3,76,2,0,148,22,0,137,4,10,...,1,1,0,0,0,0,0,1,0,0
2,4,76,1,0,99,23,0,138,4,12,...,1,1,0,0,0,0,0,1,0,0
3,5,76,1,0,148,16,0,138,3,8,...,1,1,0,0,0,0,0,1,0,1
4,5,50,0,0,148,25,0,137,4,11,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,1,0,0,0,0,0,1,0,0
395,51,70,0,2,220,68,2,137,4,8,...,1,1,0,0,1,1,0,1,0,1
396,51,70,3,0,110,115,6,134,2,9,...,1,1,0,0,1,1,0,0,0,0
397,51,90,0,0,207,80,6,142,5,8,...,1,1,0,0,1,1,0,1,0,1
398,51,80,0,0,100,49,1,140,5,16,...,1,1,0,0,0,0,0,1,0,0

In [76]:
independent.shape

(399, 27)

In [78]:
dependent=dataset[['classification_yes']]

In [79]:
dependent

     classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [80]:
dependent.shape

(399, 1)

In [81]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [82]:
x_train

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
240,60,100,0,3,263,27,1,135,4,12,...,1,1,0,0,1,1,1,1,0,0
218,57,80,0,0,120,48,1,137,4,11,...,1,1,0,0,1,1,0,1,0,0
101,42,70,0,0,75,31,1,141,3,16,...,1,1,0,0,0,0,0,1,0,0
311,66,70,1,0,248,30,1,138,5,12,...,1,1,0,0,1,1,0,1,0,0
194,55,80,0,0,146,57,3,137,4,9,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,68,70,0,0,98,86,4,135,3,9,...,1,1,0,0,1,1,1,0,1,0
192,54,90,1,0,150,18,1,140,4,12,...,1,0,0,0,0,0,0,0,1,1
117,45,80,0,0,107,15,1,141,4,11,...,1,0,0,0,0,0,0,1,0,0
47,30,80,0,0,89,42,0,139,5,16,...,1,1,0,0,0,0,0,1,0,0
172,51,60,0,0,129,25,1,139,5,17,...,1,1,0,0,0,0,0,1,0,0

In [83]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
param_grid={ "criterion": ["gini", "entropy"],
    "max_depth": [3, 5, 8, 12],
    "min_samples_split": [10, 20, 50],
    "min_samples_leaf": [5, 10, 20],
    "max_features": ["sqrt", "log2"],
    "ccp_alpha": [0.0, 0.001, 0.01, 0.1]}
grid=GridSearchCV(DecisionTreeClassifier(), param_grid,refit=True, verbose=3, n_jobs=-1,scoring='accuracy')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 576 candidates, totalling 2880 fits

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'ccp_alpha': [0.0, 0.001, 0.01, 0.1],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 5, 8, 12],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [5, 10, 20],
                         'min_samples_split': [10, 20, 50]},
             scoring='accuracy', verbose=3)

In [84]:
re=grid.cv_results_

In [85]:
re

{'mean_fit_time': array([0.00734949, 0.0107573 , 0.00888705, 0.00600901, 0.00553164,
        0.00477972, 0.0069478 , 0.00558028, 0.00598273, 0.005232  ,
        0.00538216, 0.00654135, 0.00503807, 0.00648561, 0.00505724,
        0.00586362, 0.00541377, 0.00584536, 0.0060617 , 0.00640302,
        0.00573115, 0.00731087, 0.00628066, 0.00642715, 0.0055367 ,
        0.00649824, 0.00767145, 0.0061727 , 0.00649819, 0.0061542 ,
        0.00680642, 0.00590544, 0.00524235, 0.00584493, 0.00500655,
        0.00513372, 0.00596347, 0.00507054, 0.00619078, 0.00622473,
        0.00553441, 0.006072  , 0.00618005, 0.00579133, 0.00553355,
        0.00621228, 0.00605731, 0.00547299, 0.00519323, 0.00585489,
        0.00529814, 0.00518751, 0.00604658, 0.00512528, 0.00589728,
        0.00474086, 0.00520396, 0.00565629, 0.00564904, 0.00541291,
        0.00512023, 0.00582786, 0.00535541, 0.00621014, 0.00491524,
        0.00585766, 0.00575075, 0.00525041, 0.00616307, 0.00558677,
        0.00601206, 0.0060564 , 0.0053937 , 0.00573211, 0.00510864,
        0.00499082, 0.00558777, 0.0057641 , 0.00568886, 0.00472202,
        0.00531058, 0.00534234, 0.00523052, 0.00513859, 0.00564694,
        0.00526872, 0.00522323, 0.00555749, 0.00596924, 0.00537348,
        0.00571532, 0.0056428 , 0.0056036 , 0.00509577, 0.0058598 ,
        0.00522981, 0.00542474, 0.00590158, 0.00484767, 0.00563855,
        0.00601702, 0.00504847, 0.00544715, 0.00555015, 0.00519719,
        0.00520015, 0.00533009, 0.00521493, 0.00531464, 0.00580068,
        0.00541553, 0.00593748, 0.00593133, 0.00575991, 0.00555925,
        0.00571823, 0.00565805, 0.00589247, 0.00519462, 0.00573344,
        0.00536594, 0.0041801 , 0.00546799, 0.00550466, 0.00467963,
        0.0055047 , 0.0057261 , 0.00453639, 0.00538096, 0.00591455,
        0.00520401, 0.00553064, 0.00515127, 0.00614033, 0.00523076,
        0.00548449, 0.00519719, 0.0055481 , 0.00580301, 0.00558414,
        0.00533938, 0.00559349, 0.00562825, 0.00547514, 0.00533571,
        0.00562129, 0.00559759, 0.00538645, 0.00605521, 0.00594296,
        0.0054225 , 0.00595717, 0.00575924, 0.00564485, 0.00547314,
        0.00596833, 0.00532074, 0.00557261, 0.00549345, 0.00555968,
        0.00536351, 0.00590773, 0.00530953, 0.00499554, 0.00541954,
        0.00510874, 0.00545144, 0.00563078, 0.00551462, 0.00522218,
        0.0058764 , 0.00535212, 0.00607824, 0.00531321, 0.0056088 ,
        0.00578446, 0.00602732, 0.00563536, 0.00560408, 0.00545359,
        0.00579553, 0.00561242, 0.00557065, 0.00519037, 0.0056673 ,
        0.00510888, 0.00552959, 0.0057827 , 0.00588412, 0.00585847,
        0.0056088 , 0.00552649, 0.00530367, 0.00537658, 0.00563607,
        0.00560846, 0.00640874, 0.00550179, 0.00574856, 0.0069407 ,
        0.00587831, 0.00561991, 0.00603223, 0.00559049, 0.0053061 ,
        0.00572577, 0.00594325, 0.00534043, 0.00647116, 0.0065876 ,
        0.0055759 , 0.00605979, 0.00591226, 0.00569544, 0.00572743,
        0.00608668, 0.00602422, 0.00619016, 0.0068048 , 0.00541806,
        0.00505729, 0.00619779, 0.00636868, 0.00602822, 0.00636678,
        0.0057683 , 0.00695734, 0.00660319, 0.00584207, 0.00526042,
        0.00535674, 0.0059895 , 0.00643692, 0.00629835, 0.00563869,
        0.00651689, 0.00575986, 0.0058979 , 0.00631552, 0.00529261,
        0.00560746, 0.00585895, 0.00655394, 0.00602536, 0.00579057,
        0.00589786, 0.00599732, 0.00571098, 0.00634108, 0.0055346 ,
        0.00574656, 0.00569439, 0.00598435, 0.00604267, 0.00640535,
        0.00579576, 0.00603528, 0.00632124, 0.00610809, 0.00561547,
        0.00612044, 0.00633335, 0.00599375, 0.00576367, 0.00599728,
        0.00595822, 0.00587578, 0.00571237, 0.00507822, 0.00584025,
        0.00549703, 0.00559063, 0.00575247, 0.00534024, 0.00590606,
        0.00598865, 0.00548134, 0.00519085, 0.00537839, 0.00562   ,
        0.00615907, 0.00533452, 0.00600348, 0.00617394, 0.0053472 ,
        0.00598955, 0.0059072 , 0.00526323, 0.00609784, 0.0056078 ,
        0.00512853, 0.00537419, 0.00641336, 0.00546775, 0.00587873,
        0.00623126, 0.00587339, 0.00575476, 0.00620108, 0.00576873,
        0.00621867, 0.00578442, 0.00591426, 0.00606837, 0.00620942,
        0.00551562, 0.00593562, 0.00636888, 0.00581231, 0.00641885,
        0.005685  , 0.00602269, 0.00645475, 0.00628161, 0.00534582,
        0.00628438, 0.00518274, 0.00581346, 0.00615435, 0.00572696,
        0.00549669, 0.00580339, 0.0058032 , 0.0059072 , 0.00615997,
        0.00522566, 0.00614944, 0.00528603, 0.00582442, 0.00522394,
        0.00582871, 0.00623889, 0.00567994, 0.00595727, 0.00598087,
        0.00602789, 0.00645003, 0.00573101, 0.00573416, 0.0054554 ,
        0.00621724, 0.00624228, 0.00563631, 0.0052763 , 0.00680819,
        0.00562124, 0.00562716, 0.00652905, 0.00589433, 0.00494909,
        0.00639668, 0.0062942 , 0.00609341, 0.00613022, 0.00515094,
        0.00554028, 0.00595646, 0.00616527, 0.00558782, 0.0059937 ,
        0.00598712, 0.00603185, 0.00624299, 0.00618639, 0.00557327,
        0.00571742, 0.00573516, 0.00540657, 0.00614576, 0.00537386,
        0.00599689, 0.00488734, 0.00592513, 0.00575867, 0.0058795 ,
        0.00676522, 0.00630002, 0.00519652, 0.00601411, 0.00572324,
        0.0063385 , 0.00553842, 0.00626655, 0.00521898, 0.00574522,
        0.00555911, 0.00606608, 0.00621634, 0.0061492 , 0.00568771,
        0.0061635 , 0.00548172, 0.00547242, 0.00611115, 0.00594878,
        0.0056581 , 0.0056139 , 0.00621104, 0.00621262, 0.00536318,
        0.00536218, 0.00595303, 0.00576963, 0.00574288, 0.00589471,
        0.00604534, 0.00581975, 0.00580387, 0.00530148, 0.00621934,
        0.00623126, 0.00578394, 0.00570312, 0.00616298, 0.00660553,
        0.00608993, 0.0059916 , 0.00558772, 0.00509353, 0.00617776,
        0.006216  , 0.00628467, 0.00558209, 0.00660582, 0.0060832 ,
        0.00525284, 0.00701194, 0.00587473, 0.0062089 , 0.00609589,
        0.0059761 , 0.00635719, 0.00627484, 0.00609679, 0.00554004,
        0.00576563, 0.00531573, 0.0049859 , 0.00549278, 0.00617204,
        0.00621214, 0.00589375, 0.00552664, 0.00591135, 0.00611911,
        0.00588412, 0.00644608, 0.00601025, 0.00649657, 0.00592132,
        0.00592771, 0.00545783, 0.00629764, 0.00599289, 0.00609379,
        0.00569534, 0.00541258, 0.00563831, 0.00572438, 0.00588198,
        0.0055378 , 0.00568523, 0.00594435, 0.00609374, 0.00612597,
        0.00625639, 0.00628381, 0.005406  , 0.00652809, 0.00536017,
        0.00613165, 0.00641217, 0.00594616, 0.00502176, 0.00624132,
        0.00583768, 0.0054132 , 0.00571003, 0.00607052, 0.0057569 ,
        0.0068584 , 0.00606337, 0.00587511, 0.00581861, 0.00605798,
        0.00596504, 0.00616965, 0.00659952, 0.00591869, 0.00560966,
        0.007025  , 0.0062407 , 0.00629497, 0.00658116, 0.00648718,
        0.0061275 , 0.00618896, 0.00625601, 0.00645757, 0.00564189,
        0.00620394, 0.00627151, 0.00627217, 0.00598931, 0.00582008,
        0.00503297, 0.00600824, 0.00591154, 0.00568619, 0.00628786,
        0.00655389, 0.00663753, 0.00610895, 0.00617819, 0.00649786,
        0.00633254, 0.00480862, 0.00561604, 0.0058002 , 0.00546064,
        0.00625968, 0.00653305, 0.0052247 , 0.00649486, 0.00683446,
        0.00555496, 0.0064435 , 0.0057003 , 0.00643711, 0.0062552 ,
        0.00554671, 0.00599198, 0.00617185, 0.00561633, 0.00631094,
        0.00497618, 0.00599403, 0.00529323, 0.00568824, 0.00585914,
        0.00669928, 0.00596967, 0.00671053, 0.00552773, 0.00550766,
        0.00629215, 0.0066659 , 0.00674386, 0.00558915, 0.00618496,
        0.00635667, 0.00574389, 0.00634856, 0.00549812, 0.00630884,
        0.00659719, 0.00618334, 0.0060132 , 0.00629182, 0.00637984,
        0.00650344, 0.00586042, 0.00648069, 0.0064291 , 0.00553193,
        0.00644116, 0.00654511, 0.0053216 , 0.00581813, 0.00600891,
        0.00566869, 0.0056241 , 0.00610781, 0.00650797, 0.00647974,
        0.00571432]),
 'std_fit_time': array([9.06365819e-04, 3.74616987e-03, 2.15926078e-03, 4.33485986e-04,
        5.77429020e-04, 8.46046200e-04, 6.88396503e-04, 4.82860281e-04,
        4.93737226e-04, 1.04465624e-03, 5.33502763e-04, 7.37358286e-04,
        8.10733260e-04, 1.09680504e-03, 1.12611951e-03, 1.31476205e-03,
        6.21693843e-04, 3.08950938e-04, 1.66569233e-03, 1.47322392e-03,
        3.32045184e-04, 6.59690672e-04, 1.20241961e-03, 1.12832634e-03,
        5.57627604e-04, 1.35479379e-03, 1.77700894e-03, 1.60412439e-03,
        1.80590526e-03, 8.51405433e-04, 1.06581436e-03, 4.79134305e-04,
        5.30319586e-04, 1.26380778e-03, 6.69868827e-04, 7.35584595e-04,
        5.05219053e-04, 1.11045401e-03, 9.94807308e-04, 8.70109048e-04,
        1.24668861e-03, 1.03384661e-03, 4.07041002e-04, 8.25529728e-04,
        9.16292281e-04, 5.53102645e-04, 1.00527552e-03, 5.25952241e-04,
        7.41225579e-04, 6.28951491e-04, 8.87771920e-04, 9.39713538e-04,
        6.73858899e-04, 1.05443660e-03, 6.63788513e-04, 7.10938131e-04,
        4.43433817e-04, 5.18636608e-04, 4.22359933e-04, 5.17587365e-04,
        3.82139286e-04, 3.66915377e-04, 5.05217113e-04, 4.02381668e-04,
        5.97871979e-04, 7.11064047e-04, 9.21531742e-04, 5.68417802e-04,
        5.57723596e-04, 2.76428246e-04, 8.14767839e-04, 8.05793238e-04,
        8.93330808e-04, 4.31293276e-04, 4.51353849e-04, 4.11658161e-04,
        3.49575835e-04, 3.66958821e-04, 4.88276905e-04, 6.01297642e-04,
        1.62818727e-04, 1.59510732e-04, 3.01347978e-04, 3.06303593e-04,
        3.20267740e-04, 1.97439526e-04, 3.67210416e-04, 8.75159144e-04,
        6.76516126e-04, 2.16922914e-04, 9.87271287e-04, 5.66441052e-04,
        2.01996370e-04, 1.72251865e-04, 5.89855918e-04, 4.33700778e-04,
        4.61962758e-04, 7.23875950e-04, 7.92182626e-04, 2.36003392e-04,
        8.95905548e-04, 3.35628648e-04, 4.38964670e-04, 4.79442631e-04,
        2.09675313e-04, 5.14843975e-04, 9.03609598e-04, 4.42941657e-04,
        4.36226660e-04, 4.09678396e-04, 2.87744048e-04, 6.04601135e-04,
        1.17643998e-03, 9.92211203e-04, 3.93533606e-04, 3.45082706e-04,
        8.09209651e-04, 4.73244710e-04, 5.96619072e-04, 7.83003209e-04,
        3.77071434e-04, 7.43817404e-04, 6.24851542e-04, 1.09707309e-04,
        7.01052169e-04, 8.82277093e-05, 6.62078581e-04, 9.04698605e-04,
        5.10839691e-04, 8.48016828e-04, 8.08063328e-04, 4.19159537e-04,
        4.54796098e-04, 4.14057630e-04, 5.47049850e-04, 1.75625644e-04,
        8.53409859e-04, 2.41656047e-04, 4.50769820e-04, 3.44759089e-04,
        1.78455247e-04, 2.73534817e-04, 5.97652743e-04, 4.93271840e-04,
        6.07392593e-04, 9.57873180e-04, 6.00752373e-05, 5.25390805e-04,
        3.35150708e-04, 5.12560457e-04, 4.05754173e-04, 3.60852341e-04,
        7.23965779e-04, 3.05438912e-04, 1.70376459e-04, 4.47605646e-04,
        6.86820895e-04, 6.24582352e-04, 8.07828875e-04, 1.84635818e-04,
        3.30217303e-04, 3.38456227e-04, 6.03834097e-04, 4.33832814e-04,
        1.80068283e-04, 9.34003639e-04, 2.36139082e-04, 7.12942554e-04,
        4.54588223e-04, 9.80289062e-05, 5.00630821e-04, 7.85972680e-04,
        3.13945906e-04, 4.98829090e-04, 1.99679681e-04, 3.36096444e-04,
        9.15886200e-04, 4.76654843e-04, 2.08063751e-04, 5.66680750e-04,
        7.82628070e-04, 2.23267429e-04, 2.85163372e-04, 5.88025271e-04,
        5.10326681e-04, 3.09266759e-04, 4.04227304e-04, 1.95097421e-04,
        7.48915064e-04, 5.96218702e-04, 9.07020335e-04, 2.38747627e-04,
        3.80593527e-04, 3.87137009e-04, 1.00391919e-03, 6.81866392e-04,
        4.00411022e-04, 5.16385151e-04, 2.59147436e-04, 1.26970411e-03,
        3.88501435e-04, 3.70922078e-04, 9.89002557e-04, 7.97576159e-04,
        6.85067493e-04, 3.77029704e-04, 3.20217628e-04, 2.25835364e-04,
        1.02720470e-03, 1.61680936e-03, 4.01671501e-04, 4.44375357e-04,
        1.32125059e-03, 4.83930509e-04, 5.46477781e-04, 4.11558579e-04,
        2.32644720e-04, 7.25070351e-04, 9.70962450e-04, 7.78043050e-04,
        8.18017298e-04, 8.34747084e-04, 1.32082788e-03, 1.85953311e-04,
        5.11423433e-04, 6.11799189e-04, 6.57090175e-04, 5.46319147e-04,
        5.83892048e-04, 1.32277809e-03, 3.54095029e-04, 6.45085769e-04,
        1.01995463e-03, 9.09237157e-04, 1.55778894e-03, 1.09415935e-03,
        7.07098148e-04, 5.49727227e-04, 3.11512916e-04, 8.39349693e-04,
        9.33179280e-04, 1.16207304e-03, 7.33824848e-04, 5.67917087e-04,
        8.93333839e-04, 2.86300217e-04, 3.84846069e-04, 4.70924112e-04,
        3.80921136e-04, 6.45366521e-04, 7.69905644e-04, 1.24637882e-03,
        4.67607811e-04, 8.31527613e-04, 6.43056676e-04, 6.53660969e-04,
        5.69056142e-04, 8.52385966e-04, 3.70926332e-04, 9.48219614e-04,
        8.39985908e-04, 8.85087415e-04, 8.42593395e-04, 7.37606353e-04,
        5.26931611e-04, 4.33475102e-04, 4.90350951e-04, 4.65883559e-04,
        2.97385357e-04, 1.77275743e-04, 6.13711123e-04, 3.04166286e-04,
        3.47545817e-04, 9.26681837e-04, 6.44638911e-04, 4.86296419e-04,
        7.71772889e-04, 5.30648484e-04, 2.68324603e-04, 1.12578576e-03,
        4.75331002e-04, 2.87993601e-04, 5.08557025e-04, 4.38035668e-04,
        4.23489182e-04, 3.62429210e-04, 7.29145817e-04, 1.95017514e-04,
        6.30061276e-04, 4.73771526e-04, 7.71465311e-04, 6.52217875e-04,
        6.74982739e-04, 2.44670977e-04, 4.73341993e-04, 7.17966053e-04,
        5.80386425e-04, 5.17567570e-04, 7.28438321e-04, 2.37716327e-04,
        4.38030566e-04, 3.70789525e-04, 9.10919652e-04, 7.02155832e-04,
        3.02084653e-04, 2.85215011e-04, 4.88530185e-04, 5.19976764e-04,
        9.38113841e-04, 7.13950247e-04, 7.34191680e-04, 4.95069621e-04,
        1.00700801e-03, 3.81572173e-04, 3.92797109e-04, 5.59707175e-04,
        7.15651990e-04, 7.59882833e-04, 5.28197847e-04, 6.96472369e-04,
        7.85701783e-04, 7.70244205e-04, 3.76616076e-04, 6.06886494e-04,
        2.27610035e-04, 7.89958809e-04, 4.24458481e-04, 6.07134480e-04,
        7.44518071e-04, 5.23811498e-04, 1.90860862e-04, 4.16706391e-04,
        7.76189480e-04, 5.74131198e-04, 5.54880438e-04, 3.12374723e-04,
        6.14398759e-04, 5.04810625e-04, 7.85865690e-04, 3.48814467e-04,
        7.24026360e-04, 7.22860692e-04, 7.99868765e-04, 8.17757884e-04,
        1.35675980e-03, 4.69125701e-04, 6.08639383e-04, 4.83919510e-04,
        4.72175596e-04, 1.11384625e-03, 2.96314437e-04, 1.92195213e-04,
        1.06782316e-03, 9.59487945e-04, 2.70531981e-04, 6.66812151e-04,
        1.73157648e-04, 4.32382331e-04, 7.24385910e-04, 6.00483678e-04,
        7.49044737e-04, 5.08384797e-04, 4.00772427e-04, 6.69894956e-04,
        4.50321109e-04, 8.11964588e-04, 5.72744492e-04, 7.91807684e-04,
        4.87530618e-04, 6.36706118e-04, 3.47358422e-04, 1.39423646e-03,
        7.05054612e-04, 8.40052923e-04, 4.24701102e-04, 5.43165720e-04,
        4.28727161e-04, 6.87157179e-04, 6.30227809e-04, 7.55850476e-04,
        4.21461974e-04, 8.46740144e-04, 3.28318897e-04, 6.79300080e-04,
        1.25475909e-04, 9.16653931e-04, 2.62665133e-04, 5.11029174e-04,
        1.05198578e-03, 3.19056585e-04, 5.92960161e-04, 5.83458656e-04,
        8.24584600e-04, 7.00868031e-04, 7.37793926e-04, 3.00141451e-04,
        7.81770567e-04, 3.33715636e-04, 7.82191974e-04, 4.37834216e-04,
        7.41130641e-04, 4.87390685e-04, 2.85361826e-04, 4.89149044e-04,
        6.49546159e-04, 6.78472723e-04, 2.00611145e-04, 5.34907380e-04,
        9.31111605e-04, 7.09045076e-04, 4.15477205e-04, 1.59490489e-04,
        3.80876634e-04, 1.66305502e-04, 7.54037173e-04, 5.87090480e-04,
        6.41518141e-04, 8.46953707e-04, 7.22458202e-04, 1.32529300e-03,
        2.32094304e-04, 4.27135449e-04, 1.35786425e-03, 7.18212428e-04,
        4.35583825e-04, 1.17131130e-03, 9.42420897e-04, 3.98400473e-04,
        2.15557717e-04, 4.84184898e-04, 9.91863270e-04, 9.27550242e-04,
        5.07608633e-04, 4.47056399e-04, 6.47704389e-04, 1.34838864e-03,
        1.12730378e-03, 6.73763592e-04, 9.26601011e-04, 1.55495610e-04,
        7.48456287e-04, 9.64300022e-04, 1.98400739e-04, 4.98714384e-04,
        1.15582777e-03, 5.10923514e-04, 4.68061989e-04, 1.13068796e-03,
        8.36874516e-04, 3.78242713e-04, 6.00219738e-04, 8.34229114e-04,
        5.67417513e-04, 8.72334999e-04, 5.60818871e-04, 2.51933428e-04,
        4.25610675e-04, 6.82588243e-04, 5.82105089e-04, 3.96669291e-04,
        4.45433582e-04, 5.17767598e-04, 8.54099380e-04, 3.41397723e-04,
        3.95406943e-04, 8.11412321e-04, 6.35789415e-04, 9.47289991e-04,
        1.30156592e-03, 5.85573880e-04, 8.76674874e-04, 3.61719931e-04,
        7.53223377e-04, 4.53139493e-04, 9.68423246e-04, 7.43978901e-04,
        3.05779263e-04, 6.77857365e-04, 4.66056711e-04, 9.98460886e-04,
        1.18598173e-03, 3.82011196e-04, 3.92043727e-04, 6.94834649e-04,
        1.00599927e-03, 6.34574191e-04, 8.11138713e-04, 5.20708941e-04,
        6.05651623e-04, 6.84827769e-04, 1.35643092e-03, 6.07406780e-04,
        3.09773068e-04, 1.07317285e-03, 5.80528421e-04, 1.48894655e-03,
        6.12657735e-04, 9.45374079e-04, 1.55513692e-03, 4.71833522e-04,
        6.77695111e-04, 1.69528692e-03, 1.02442714e-03, 7.50033520e-04,
        8.65800641e-04, 1.13995896e-03, 6.78790224e-04, 7.17459437e-04,
        9.49007101e-04, 1.16452283e-03, 7.46622495e-04, 5.99222389e-04,
        3.60309383e-04, 6.97994705e-04, 1.39762207e-03, 7.75232719e-04,
        7.13051011e-04, 1.52998866e-03, 6.29983737e-04, 1.26868198e-03,
        5.24246990e-04, 6.73778541e-04, 8.96341337e-04, 1.06936917e-03,
        7.57080070e-04, 7.24534164e-04, 6.00205843e-04, 1.04464418e-03,
        1.74978160e-03, 6.96555805e-04, 5.68504382e-04, 6.82770561e-04,
        6.09444966e-04, 5.21400176e-04, 3.18578435e-04, 7.55676577e-04,
        5.51244037e-04, 1.60650756e-03, 6.36460179e-04, 1.01400352e-03,
        5.81141644e-04, 1.24388316e-03, 5.56093803e-04, 5.66970169e-04,
        4.53999871e-04, 5.13775905e-04, 1.73727038e-03, 1.13175168e-03,
        6.68847069e-04, 9.59747072e-04, 4.50404776e-04, 6.19477734e-04,
        2.88212678e-04, 3.15696428e-04, 7.00923267e-04, 2.91816339e-04,
        1.83137342e-04, 1.25986143e-03, 1.10406447e-03, 1.11113180e-03,
        7.59060470e-04, 4.60286011e-04, 7.59854442e-04, 7.58158375e-04,
        2.90142014e-04, 7.85519953e-04, 7.10714570e-04, 1.16932156e-03,
        6.27140121e-04, 9.90746418e-04, 9.49466379e-04, 1.34676030e-03,
        5.17209706e-04, 8.45465813e-04, 8.34620979e-04, 7.57989016e-04]),
 'mean_score_time': array([0.00843554, 0.00758629, 0.00829463, 0.00592227, 0.00591078,
        0.00672402, 0.00611744, 0.00571885, 0.00538363, 0.00520387,
        0.00509439, 0.00626707, 0.005933  , 0.00593925, 0.0058599 ,
        0.0064959 , 0.00627317, 0.00631285, 0.00632071, 0.00646362,
        0.00733299, 0.00666795, 0.00655303, 0.00683742, 0.00620489,
        0.00809588, 0.00667396, 0.00618296, 0.00625596, 0.00568976,
        0.00586901, 0.00577049, 0.00574374, 0.00564485, 0.00527525,
        0.00626836, 0.00564308, 0.00600333, 0.00632944, 0.00635562,
        0.00564375, 0.00645304, 0.00624638, 0.00585775, 0.00636888,
        0.00594602, 0.0057786 , 0.00546794, 0.00523739, 0.00599031,
        0.00651331, 0.00561461, 0.00605402, 0.00519996, 0.00601115,
        0.0052043 , 0.00543427, 0.00545969, 0.00574145, 0.00539575,
        0.00659976, 0.00587511, 0.00588126, 0.00597701, 0.00585003,
        0.00602202, 0.0060504 , 0.00557151, 0.00693207, 0.00594172,
        0.00623336, 0.00595484, 0.00577369, 0.0056582 , 0.00585537,
        0.00622296, 0.00573101, 0.00563641, 0.00585375, 0.00576038,
        0.00567107, 0.00607057, 0.00571494, 0.00522852, 0.00585628,
        0.00574031, 0.00539756, 0.00585289, 0.00568299, 0.00538316,
        0.00609603, 0.00598679, 0.00577846, 0.00557542, 0.0057857 ,
        0.00523839, 0.00557971, 0.0063231 , 0.00500722, 0.00618052,
        0.00629921, 0.00559912, 0.00580726, 0.00594091, 0.00575776,
        0.0059514 , 0.00564928, 0.00586572, 0.00576944, 0.00568528,
        0.0060678 , 0.00569882, 0.0057106 , 0.00564666, 0.00603728,
        0.00610895, 0.00582228, 0.00575852, 0.00587668, 0.00547395,
        0.00543399, 0.00454431, 0.00577407, 0.00557389, 0.00502086,

In [87]:
format(grid.best_params_)

"{'ccp_alpha': 0.01, 'criterion': 'entropy', 'max_depth': 8, 'max_features': 'sqrt', 'min_samples_leaf': 5, 'min_samples_split': 10}"

In [88]:
table=pd.DataFrame.from_dict(re)

In [89]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_ccp_alpha,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007349,0.000906,0.008436,0.002073,0.0,gini,3,sqrt,5,10,"{'ccp_alpha': 0.0, 'criterion': 'gini', 'max_d...",0.944444,0.962264,0.867925,0.962264,0.981132,0.943606,0.039580,27
1,0.010757,0.003746,0.007586,0.000662,0.0,gini,3,sqrt,5,20,"{'ccp_alpha': 0.0, 'criterion': 'gini', 'max_d...",0.888889,0.924528,0.905660,0.981132,0.943396,0.928721,0.031932,112
2,0.008887,0.002159,0.008295,0.000683,0.0,gini,3,sqrt,5,50,"{'ccp_alpha': 0.0, 'criterion': 'gini', 'max_d...",0.907407,0.811321,0.905660,0.943396,0.962264,0.906010,0.052020,323
3,0.006009,0.000433,0.005922,0.000822,0.0,gini,3,sqrt,10,10,"{'ccp_alpha': 0.0, 'criterion': 'gini', 'max_d...",0.944444,0.849057,0.924528,0.962264,0.905660,0.917191,0.038996,232
4,0.005532,0.000577,0.005911,0.000673,0.0,gini,3,sqrt,10,20,"{'ccp_alpha': 0.0, 'criterion': 'gini', 'max_d...",0.944444,0.754717,0.886792,0.924528,0.886792,0.879455,0.066216,480
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
571,0.005624,0.001347,0.006083,0.001415,0.1,entropy,12,log2,10,20,"{'ccp_alpha': 0.1, 'criterion': 'entropy', 'ma...",0.870370,0.905660,0.849057,0.886792,0.962264,0.894829,0.038530,393
572,0.006108,0.000517,0.005952,0.000276,0.1,entropy,12,log2,10,50,"{'ccp_alpha': 0.1, 'criterion': 'entropy', 'ma...",0.962963,0.867925,0.905660,0.981132,1.000000,0.943536,0.049256,33
573,0.006508,0.000845,0.006332,0.001096,0.1,entropy,12,log2,20,10,"{'ccp_alpha': 0.1, 'criterion': 'entropy', 'ma...",0.833333,0.905660,0.849057,0.924528,0.962264,0.894969,0.047799,388
574,0.006480,0.000835,0.005743,0.000203,0.1,entropy,12,log2,20,20,"{'ccp_alpha': 0.1, 'criterion': 'entropy', 'ma...",0.944444,0.981132,0.811321,0.924528,0.886792,0.909644,0.057849,296
575,0.005714,0.000758,0.005213,0.000299,0.1,entropy,12,log2,20,50,"{'ccp_alpha': 0.1, 'criterion': 'entropy', 'ma...",0.925926,0.792453,0.849057,0.924528,0.905660,0.879525,0.051713,479

In [92]:
grid_pridictions=grid.predict(x_test)

In [94]:
grid_pridictions

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0])

In [95]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_pridictions)

In [96]:
print(cm)

[[49  2]
 [ 8 74]]

In [97]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_pridictions)

In [98]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.86      0.96      0.91        51
           1       0.97      0.90      0.94        82

    accuracy                           0.92       133
   macro avg       0.92      0.93      0.92       133
weighted avg       0.93      0.92      0.93       133