In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset["classification"].value_counts()

classification
yes    249
no     150
Name: count, dtype: int64

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [6]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [7]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [8]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [9]:
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2,76,3,0,148,57,3,137,4,12,...,1,0,0,0,0,0,0,1,1,0
1,3,76,2,0,148,22,0,137,4,10,...,1,1,0,0,0,0,0,1,0,0
2,4,76,1,0,99,23,0,138,4,12,...,1,1,0,0,0,0,0,1,0,0
3,5,76,1,0,148,16,0,138,3,8,...,1,1,0,0,0,0,0,1,0,1
4,5,50,0,0,148,25,0,137,4,11,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,1,0,0,0,0,0,1,0,0
395,51,70,0,2,220,68,2,137,4,8,...,1,1,0,0,1,1,0,1,0,1
396,51,70,3,0,110,115,6,134,2,9,...,1,1,0,0,1,1,0,0,0,0
397,51,90,0,0,207,80,6,142,5,8,...,1,1,0,0,1,1,0,1,0,1
398,51,80,0,0,100,49,1,140,5,16,...,1,1,0,0,0,0,0,1,0,0

In [13]:
dependent=dataset[['classification_yes']]

In [14]:
dependent.shape

(399, 1)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [16]:
x_train

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
240,60,100,0,3,263,27,1,135,4,12,...,1,1,0,0,1,1,1,1,0,0
218,57,80,0,0,120,48,1,137,4,11,...,1,1,0,0,1,1,0,1,0,0
101,42,70,0,0,75,31,1,141,3,16,...,1,1,0,0,0,0,0,1,0,0
311,66,70,1,0,248,30,1,138,5,12,...,1,1,0,0,1,1,0,1,0,0
194,55,80,0,0,146,57,3,137,4,9,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,68,70,0,0,98,86,4,135,3,9,...,1,1,0,0,1,1,1,0,1,0
192,54,90,1,0,150,18,1,140,4,12,...,1,0,0,0,0,0,0,0,1,1
117,45,80,0,0,107,15,1,141,4,11,...,1,0,0,0,0,0,0,1,0,0
47,30,80,0,0,89,42,0,139,5,16,...,1,1,0,0,0,0,0,1,0,0
172,51,60,0,0,129,25,1,139,5,17,...,1,1,0,0,0,0,0,1,0,0

In [17]:
x_train.shape

(266, 27)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
param_grid={"solver": ["lbfgs"],
    "penalty": ["l2"],
    "C": [0.01, 0.1, 1, 10],
    "class_weight": [None, "balanced"],
    "max_iter": [300, 500]}
grid=GridSearchCV(LogisticRegression(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\ANACONDA\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ANACONDA\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10],
                         'class_weight': [None, 'balanced'],
                         'max_iter': [300, 500], 'penalty': ['l2'],
                         'solver': ['lbfgs']},
             scoring='f1_weighted', verbose=3)

In [19]:
re=grid.cv_results_

In [20]:
print(re)

{'mean_fit_time': array([0.11061554, 0.15517621, 0.10043674, 0.14084954, 0.07963595,
       0.1060699 , 0.07966213, 0.11015821, 0.0735147 , 0.13418126,
       0.10096245, 0.13099656, 0.07403297, 0.11577358, 0.08192034,
       0.10086694]), 'std_fit_time': array([0.01776839, 0.01575464, 0.01761215, 0.0129917 , 0.00673029,
       0.00771611, 0.00365961, 0.01312867, 0.01228615, 0.00730891,
       0.00454744, 0.0188191 , 0.00582333, 0.01781595, 0.00728071,
       0.00847882]), 'mean_score_time': array([0.01792917, 0.01863379, 0.01907773, 0.01559248, 0.01458154,
       0.01418781, 0.01556678, 0.01772952, 0.01468954, 0.01779914,
       0.01645265, 0.01705127, 0.01551318, 0.0175859 , 0.01292391,
       0.01079459]), 'std_score_time': array([0.00462975, 0.00423145, 0.00072344, 0.00330982, 0.00278312,
       0.00161463, 0.00177836, 0.00348116, 0.00183029, 0.00307385,
       0.00314532, 0.00411328, 0.00295609, 0.00582972, 0.00330754,
       0.00053337]), 'param_C': masked_array(data=[0.01, 0.01, 0.01, 0.01, 0.1, 0.1, 0.1, 0.1, 1.0, 1.0,
                   1.0, 1.0, 10.0, 10.0, 10.0, 10.0],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=1e+20), 'param_class_weight': masked_array(data=[None, None, 'balanced', 'balanced', None, None,
                   'balanced', 'balanced', None, None, 'balanced',
                   'balanced', None, None, 'balanced', 'balanced'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_max_iter': masked_array(data=[300, 500, 300, 500, 300, 500, 300, 500, 300, 500, 300,
                   500, 300, 500, 300, 500],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=999999), 'param_penalty': masked_array(data=['l2', 'l2', 'l2', 'l2', 'l2', 'l2', 'l2', 'l2', 'l2',
                   'l2', 'l2', 'l2', 'l2', 'l2', 'l2', 'l2'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_solver': masked_array(data=['lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs',
                   'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs',
                   'lbfgs', 'lbfgs', 'lbfgs', 'lbfgs'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'C': 0.01, 'class_weight': None, 'max_iter': 300, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 0.01, 'class_weight': None, 'max_iter': 500, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 0.01, 'class_weight': 'balanced', 'max_iter': 300, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 0.01, 'class_weight': 'balanced', 'max_iter': 500, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 0.1, 'class_weight': None, 'max_iter': 300, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 0.1, 'class_weight': None, 'max_iter': 500, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 0.1, 'class_weight': 'balanced', 'max_iter': 300, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 0.1, 'class_weight': 'balanced', 'max_iter': 500, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 1, 'class_weight': None, 'max_iter': 300, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 1, 'class_weight': None, 'max_iter': 500, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 1, 'class_weight': 'balanced', 'max_iter': 300, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 1, 'class_weight': 'balanced', 'max_iter': 500, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 10, 'class_weight': None, 'max_iter': 300, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 10, 'class_weight': None, 'max_iter': 500, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 10, 'class_weight': 'balanced', 'max_iter': 300, 'penalty': 'l2', 'solver': 'lbfgs'}, {'C': 10, 'class_weight': 'balanced', 'max_iter': 500, 'penalty': 'l2', 'solver': 'lbfgs'}], 'split0_test_score': array([0.92656726, 0.92656726, 0.90850063, 0.90850063, 0.94470736,
       0.94470736, 0.92656726, 0.92656726, 0.96296296, 0.96296296,
       0.98156912, 0.98156912, 0.98156912, 0.98156912, 0.98156912,
       0.98156912]), 'split1_test_score': array([0.92351003, 0.92351003, 0.96263579, 0.96263579, 0.98101383,
       0.98101383, 0.98101383, 0.98101383, 0.9245283 , 0.9436995 ,
       0.9436995 , 0.9436995 , 0.9245283 , 0.96226415, 0.9436995 ,
       0.96226415]), 'split2_test_score': array([0.92552426, 0.92552426, 0.92552426, 0.92552426, 0.94402307,
       0.94402307, 0.92552426, 0.92552426, 0.94402307, 0.94402307,
       0.94402307, 0.962573  , 0.94402307, 0.98121703, 0.92552426,
       0.98121703]), 'split3_test_score': array([0.962573  , 0.925146  , 0.92552426, 0.92552426, 0.90608517,
       0.925146  , 0.925146  , 0.925146  , 0.9436511 , 0.96226415,
       0.9436511 , 0.9436511 , 0.96226415, 0.96226415, 0.96226415,
       0.96226415]), 'split4_test_score': array([0.942332  , 0.942332  , 0.96226415, 0.96226415, 0.96182604,
       0.96182604, 1.        , 0.98103098, 0.98103098, 0.98103098,
       0.96182604, 0.98103098, 0.98103098, 0.96182604, 0.96182604,
       0.98103098]), 'mean_test_score': array([0.93610131, 0.92861591, 0.93688982, 0.93688982, 0.94753109,
       0.95134326, 0.95165027, 0.94785647, 0.95123928, 0.95879613,
       0.95495377, 0.96250474, 0.95868312, 0.9698281 , 0.95497661,
       0.97366909]), 'std_test_score': array([0.01483836, 0.00692815, 0.02177618, 0.02177618, 0.02475271,
       0.01883692, 0.03229278, 0.02708388, 0.01922561, 0.01392789,
       0.01502993, 0.0168272 , 0.02198858, 0.00944478, 0.01898314,
       0.0093137 ]), 'rank_test_score': array([15, 16, 13, 13, 12,  9,  8, 11, 10,  4,  7,  3,  5,  2,  6,  1],
      dtype=int32)}

In [22]:
grid_predictions=grid.predict(x_test)

In [23]:
grid_predictions

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0])

In [24]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [25]:
print(cm)

[[50  1]
 [ 3 79]]

In [26]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [27]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        51
           1       0.99      0.96      0.98        82

    accuracy                           0.97       133
   macro avg       0.97      0.97      0.97       133
weighted avg       0.97      0.97      0.97       133