In [46]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")

In [47]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [48]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [49]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [50]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [51]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [52]:
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [53]:
dependent=dataset[['charges']]

In [54]:
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.20,random_state=0)

In [56]:
x_train,x_test,y_train,y_test

(      age  bmi  children  sex_male  smoker_yes
 621    37   34         4         1           1
 194    18   34         0         1           0
 240    23   36         2         0           1
 1168   32   35         2         1           0
 1192   58   32         1         0           0
 ...   ...  ...       ...       ...         ...
 763    27   26         0         1           0
 835    42   35         2         1           0
 1216   40   25         0         1           0
 559    19   35         0         1           0
 684    33   18         1         0           0

 [1070 rows x 5 columns],
       age  bmi  children  sex_male  smoker_yes
 578    52   30         1         1           0
 610    47   29         1         0           0
 569    48   40         2         1           1
 1034   61   38         0         1           0
 198    51   18         0         0           0
 ...   ...  ...       ...       ...         ...
 1084   62   30         2         0           0
 726    41   28         1         1           0
 1132   57   40         0         1           0
 725    30   39         3         0           1
 963    46   24         3         1           0

 [268 rows x 5 columns],
       charges
 621     40182
 194      1137
 240     38511
 1168     4670
 1192    13019
 ...       ...
 763      3070
 835      7160
 1216     5415
 559      1646
 684      4766

 [1070 rows x 1 columns],
       charges
 578      9724
 610      8547
 569     45702
 1034    12950
 198      9644
 ...       ...
 1084    15019
 726      6664
 1132    20709
 725     40932
 963      9500

 [268 rows x 1 columns])

In [57]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor()
regressor.fit(x_train,y_train)

C:\ANACONDA\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [58]:
y_pred=regressor.predict(x_test)

In [59]:
y_pred

array([11314.641     ,  9551.39      , 44783.63866667, 13224.12      ,
        9255.53      , 13190.08      ,  1816.3675    , 12168.52333333,
        7025.44      ,  5035.15      ,  7284.70666667, 17305.78      ,
       13901.752     ,  6089.57      , 19936.53      , 13038.96      ,
       13864.073     ,  6254.89      ,  6956.6       , 33635.98      ,
       23905.43857143, 13153.45666667, 11898.55      , 24863.79      ,
        6518.45145238,  4938.38      ,  6317.316     ,  8064.82      ,
        3736.51      ,  9785.86      ,  7866.385     , 48254.38      ,
       14027.98      , 11168.61      , 17291.9       ,  3852.295     ,
        8713.19      , 37790.28      , 39705.08      ,  4026.74333333,
       11222.7       ,  3609.025     , 20957.29      , 46483.62      ,
       36769.49      ,  4437.26      , 15069.66      ,  6654.68      ,
        5030.69      , 12280.18      ,  4239.065     ,  9331.95      ,
       24933.831     , 49660.38      , 11791.27666667,  7725.73      ,
        2938.24833333, 10665.85      ,  9234.09      , 16942.77      ,
        1518.688     , 46891.99      , 16863.31116667, 20131.325     ,
       14997.44      , 10155.57      , 33635.98      , 40435.29      ,
        5011.76      , 11808.17      , 20058.19933333, 11734.63      ,
       19385.82      , 13914.1       , 13638.005     , 16171.04083333,
        8872.485     , 13240.03      , 19147.35      , 48283.89      ,
       11620.52433333, 51312.84      ,  4616.53761905, 10995.44      ,
       41253.59      , 18954.37      ,  3396.57      ,  3154.88733333,
       13613.25      , 39274.2       ,  5778.74      , 10978.155     ,
        3102.492     , 13105.12      ,  5181.73      ,  4507.13      ,
       43583.14      , 42917.245     ,  5111.35      , 10810.49657143,
        2994.0625    ,  6753.05266667,  8536.965     , 38907.67      ,
       30930.36      ,  3570.54      , 11179.48      ,  3481.9605    ,
       11647.96      , 45643.47      , 12341.27      ,  7566.74      ,
       10177.245     , 34164.55      , 47224.48      ,  7147.51      ,
        2115.67      , 10665.85      , 23113.05      ,  9249.91      ,
       42574.4       , 13551.52      , 14573.7       ,  8038.47      ,
       12763.03016667,  5621.66      , 23921.49      , 27151.68      ,
       48182.18      ,  1628.58483333, 22478.91666667,  4789.2665    ,
        5834.49      ,  9065.93      , 43306.98      , 39544.97      ,
       24843.11      , 16712.76      , 24106.6       ,  7779.6775    ,
        2090.32033333, 11563.535     , 11382.53      , 10897.265     ,
        6764.02616667, 14237.49      , 23191.56      , 13693.06      ,
        1472.34783333, 13023.64      ,  5981.3425    , 39844.1       ,
       11035.985     ,  8702.25366667,  4835.4925    ,  6552.80266667,
        4213.10780952,  8166.36      , 13038.96      , 10678.03      ,
        8716.91      , 13281.68      , 15738.49      ,  9336.72      ,
        4078.97      ,  9333.244     , 15427.03      ,  6059.79      ,
        4249.99      ,  3838.347     , 10560.81      ,  4762.15      ,
       11695.46      ,  2370.83833333, 11383.96      , 10026.99      ,
        5318.16      ,  7482.16333333, 27953.65      ,  1671.222     ,
       15827.16666667,  6800.79      , 11308.59333333,  7830.18      ,
        8952.24      , 28142.98      ,  5420.35228571,  3492.16666667,
       14243.55      , 10511.4       , 41808.16      ,  5243.59      ,
        5630.37      , 25811.506     ,  2986.17833333,  3176.295     ,
        7128.06      ,  5976.3       ,  9316.63      ,  4269.31      ,
       11402.86      , 47064.74      , 16822.87666667, 18388.89      ,
        8797.3       , 42567.822     ,  4853.84      ,  9918.976     ,
        7593.93666667,  2455.89083333, 10082.4       , 13635.63      ,
        5955.37      ,  4821.35166667,  6559.47633333,  4850.35      ,
        6992.67690476,  6805.35      , 14230.235     ,  6806.89380952,
        8551.8       ,  7904.43333333, 11071.188     ,  8954.36      ,
       12520.24      , 14810.27      , 19601.32      , 11967.906     ,
        7022.44333333,  2740.07      ,  4956.70096032,  8412.46133333,
       14665.26      ,  6740.395     ,  5045.1       ,  7138.79      ,
       11988.88      , 34252.39      ,  5603.5825    , 12241.55      ,
        6039.72666667, 37487.63433333,  8642.22      ,  6918.82966667,
       10530.65      , 17031.27      ,  5116.38      ,  8453.485     ,
        2778.54      ,  7115.1575    , 20192.81      , 46919.73      ,
        4074.74      ,  4334.47      ,  3704.59347619,  1723.26440476,
        9136.61      ,  2694.86866667,  9164.55      ,  9374.19      ,
        8794.034     , 24745.615     , 46235.11      , 17416.79333333,
        6559.47633333, 11214.24657143, 45921.78      ,  9553.79      ])

In [60]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [61]:
r_score

0.8746036529188597

In [65]:
import pickle

In [66]:
filename="final_model_Random_forest_regression.sav"
pickle.dump(regressor,open(filename,'wb'))

In [68]:
loaded_model=pickle.load(open("final_model_Random_forest_regression.sav",'rb'))
result=loaded_model.predict([[1192,58,32,1,0]])

C:\ANACONDA\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [69]:
result

array([25186.13])