In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")

In [2]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [8]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [12]:
x_test

      age  bmi  children  sex_male  smoker_yes
578    52   30         1         1           0
610    47   29         1         0           0
569    48   40         2         1           1
1034   61   38         0         1           0
198    51   18         0         0           0
...   ...  ...       ...       ...         ...
1261   28   37         1         1           0
494    21   25         4         1           1
97     55   38         0         1           0
418    64   39         1         1           0
920    62   25         0         0           0

[402 rows x 5 columns]

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [16]:
x_train

array([[-1.5330973 , -0.36100765, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.278355  , -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.51612426,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.84052963, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.75787698, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.95941426, -0.06746417, -0.97676557, -0.50466988]])

In [46]:
from sklearn.svm import SVR
regressor=SVR(kernel='linear',C=100,gamma=0.1,epsilon=0.5)
regressor.fit(x_train,y_train)

C:\ANACONDA\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100, epsilon=0.5, gamma=0.1, kernel='linear')

In [47]:
weight=regressor.intercept_
weight

array([10411.66336881])

In [48]:
bias=regressor.n_support_
bias

array([936], dtype=int32)

In [49]:
regressor.support_

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935],
      dtype=int32)

In [50]:
y_pred=regressor.predict(x_test)

In [51]:
y_pred

array([10222.0784048 ,  9230.60575924, 25883.9130359 , 12378.53276153,
        9615.18954195,  4882.03984977,  1149.2611865 , 11247.34513933,
        7690.80635899,  5533.35660553,  6374.95422676, 10344.07895269,
        8180.96495956,  5037.01212481, 19285.19510602, 10791.32669755,
       11777.30813836,  3447.81526738,  6922.9802601 , 17496.72576706,
       26283.92715193, 12087.94736383, 10168.01210467, 24853.97745843,
        2023.52981354,  5143.28161806,  3555.55391359,  8288.22984953,
        4536.39275521,  8784.05268976,  8167.22469836, 28395.78058084,
       12616.74193122, 10779.87053179, 18649.13564867,  4322.38461576,
        9240.07113155, 20140.0592322 , 23935.80257895,  1843.48879797,
        5703.23757341,  3715.19503158, 22385.71544458, 28411.21091416,
       17461.89093288,  2879.38933644, 10767.12566732,  7501.17228468,
        4576.02411876, 11709.50157703,  2654.92042796,  2632.40946984,
       25194.65498871, 27342.16561362, 12008.68463674,  3646.39307352,
        3121.57267368,  9201.60819964,  9334.76419195, 12176.15382275,
        1115.29406262, 29714.49121683, 13191.65446364, 10144.50574982,
       10489.97980948, 10522.25686124, 17234.31556714, 21676.57914028,
        2613.17800388,  8269.69305896, 12481.30184347, 11461.52631369,
       17424.12267636, 13199.73048517, 12122.08752262, 12194.69061332,
        8055.16327903,  8521.64248985, 22580.31908317, 28799.59582952,
       11169.25084388, 24264.15623318,  1999.32878331,  8385.20700537,
       24027.81017052, 21847.15478355,  4034.60495397,  3024.76855275,
       11986.34671353, 20241.83291741,  6285.75237111, 10586.26228993,
        3349.14803942,  9056.22898333,  5196.6532428 ,  5342.85482092,
       26681.08276421, 24592.2619339 ,  5503.49133563, 11114.88382241,
        2261.73898323,  6096.1182968 ,  4740.46176611, 21792.09308669,
       24417.88515799,  3389.9478346 , 10679.26527822,  3966.97142755,
       11494.49804085, 28041.53582427, 11671.56028559,  5186.71411424,
        9468.81492892, 16996.10639745, 27895.16121124,  7900.01796908,
        1631.34376554,  9201.60819964, 12228.35701586,  9324.30342291,
       24849.70256954,  9877.59974187, 13534.74377579,  5416.15258701,
        8394.97309901,  4688.258573  , 25228.62211259, 24661.06389195,
       28210.9430359 ,  1833.72270432,  8842.22084387,  1372.73469826,
        6893.1149902 ,  9367.21427862, 23269.75016527, 21170.46856592,
       23124.54398387, 10271.47586199, 26706.27919117,  2539.57951646,
        1795.0867375 , 10537.86022946, 10003.10070107, 10396.45518071,
        5377.6896551 , 13437.93965485, 12548.93536989,  3186.40046419,
         945.88685099, 10625.89365347,  6820.5118995 , 19624.00952928,
       10008.07026535,  1300.13160756,  2125.13046384,  7393.7343598 ,
        2373.97343747,  1275.93057733, 10791.32669755, 10125.10124896,
        4507.91683609, 12665.14399169, 12146.28855285, 10177.47747698,
        4677.79780396,  4143.73295096, 17361.28567931,  5853.93495956,
        4614.66008558,  1463.87457953,  4133.27218193,  4226.27517022,
        8604.01167419,  2596.75227385,  4459.51477562,  4406.14315088,
        4129.47104928,  6592.93653376, 28903.05958684,   804.48180224,
       10989.90450369,  7083.61677481, 11232.08784093,  3335.58081314,
        5703.9322488 , 28421.15004271,  1975.12775308,  2335.33747065,
       13365.33656416, 10251.0759644 , 25393.23279485,  4118.83724534,
        6247.2894392 , 24699.00518339,  2859.16247376,  2354.74197152,
        6660.57006018,  6523.96154079,  4754.8967027 ,  4663.06214604,
       11140.08024936, 29115.37765418, 11801.33613368, 21458.76986819,
        4609.6905213 , 25470.63241492,  3390.64250999,  9920.03684134,
        6625.735226  ,  1215.8993162 ,  9220.83966559, 12816.31513409,
        4969.90023887,  2630.71939772,  7287.16414523,  2306.33991105,
        6748.60348419,  5387.45574874, 13128.81746658,  6714.93708165,
        6834.77380118,  7783.80934728,  9069.96924453,  2913.52949523,
       11815.07639488, 13141.56233106, 12184.75148476, 11621.46815301,
        7128.21770263,  2617.15217144,   901.28592317,  8865.42647738,
       12125.88865526,  2865.64907525,  5149.24657906,  7782.81395056,
        9444.61389869, 18570.56759697,  6499.93354547, 11058.70646175,
        6421.66621511, 18814.26797141,  8248.59848598,  7685.31515423,
        8658.07797432, 10508.68963495,  2365.20274055,  8301.97011072,
        2126.29889548,  7166.15899406, 20816.05077444, 29971.23717708,
        4239.8423965 ,  3772.19475405,  1221.8642772 ,   707.67768131,
        8457.81009607,  1391.27148883,  4236.73593925,  3837.19557946,
        8940.88807183, 26040.05374258, 28566.35622411, 13589.80547264,
        7287.16414523, 11377.29402233, 21879.95347579,  9300.10239268,
       23649.88602419,   998.0900441 , 19571.63330126,  5493.72524199,
       12189.72104904,  3783.82395472, 22215.13980132,  5916.07728122,
       10109.84395056,  9835.38356155,  1873.35406787, 12617.73732795,
       11669.87021348,  5220.85427303, 11898.31328952,  1246.06530743,
        6717.74281757,  3458.27603641,  8847.71204863, 24154.78028268,
        3786.62969064,   780.28077201,  1719.37718955, 29144.37521378,
        9313.84265388,  5104.64565123, 11825.53716391, 11402.49044928,
       18652.93678131,  7345.33229934,  5761.10500618,  9443.61850196,
        1163.69612309,  2247.99872203, 19899.0443266 , 19533.17036935,
       12767.91307362,  2641.35320167,  3530.18445172,  9110.29528346,
        9895.8358111 , 17098.87547939, 22192.6288432 ,  6572.36360126,
       17647.89690946,  1508.47550735,  6940.52165394,  5196.6532428 ,
        8710.75492368,  1481.16801986,  7364.7368002 , 24332.95819123,
        3190.20159683,  4055.00485156,  1314.86726549,  9190.97439569,
        4253.5826577 , 11548.86506232, 29859.00272284, 20724.91089317,
        9459.04883528, 24523.45997584, 12374.55859398,  4633.89155153,
        9959.66820488,  3579.28118758, 28576.12231775,  5294.45276046,
       12336.09566207,  1417.33562609, 17696.29896992,  3151.73866492,
       27494.20446632,  7022.89083828,  2306.33991105, 19317.99379827,
        5591.52475964,  5872.64478504, 29772.65937094,  1163.69612309,
        8585.47488362,  1888.78440118, 11399.21095712,  3477.98125861,
        6187.95285345,  5270.94640561, 26253.06648531,  8924.76306313,
       21914.09363458, 18589.79906292,  6499.93354547,  8906.74791304,
        1091.09303239,  3462.5509253 ,  2306.16687614,  9317.64378652,
       27313.16805402, 10965.87650837,  1363.26932595, 11514.89793844,
        2154.30105835,  8403.74379593,  4138.2417462 ,  2479.54825532,
        3375.21217668, 17379.52174854,  6608.36686707,  1004.0550051 ,
       22525.9520617 , 11057.71106502, 26263.52725434, 11228.28670829,
        5046.47749712,  1922.92455997,  1722.4836468 , 10465.08410385,
        5688.50191548,  1270.26633766, 10566.85778906,  7642.40429853,
        7102.32660029,  4118.83724534,  2509.71424656, 21087.92634667,
        1712.71755316,  9522.18655366,  1439.67354929,  8208.96712244,
       11090.68279217,  4093.64081838, 19233.5135534 , 10804.07156202,
       13588.81007592, 12671.10895269])

In [52]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [53]:
r_score

0.6289638110938837