In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [9]:
dataset['classification_yes'].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [10]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [11]:
independent

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
0,2,76,3,0,148,57,3,137,4,12,...,1,0,0,0,0,0,0,1,1,0
1,3,76,2,0,148,22,0,137,4,10,...,1,1,0,0,0,0,0,1,0,0
2,4,76,1,0,99,23,0,138,4,12,...,1,1,0,0,0,0,0,1,0,0
3,5,76,1,0,148,16,0,138,3,8,...,1,1,0,0,0,0,0,1,0,1
4,5,50,0,0,148,25,0,137,4,11,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,1,0,0,0,0,0,1,0,0
395,51,70,0,2,220,68,2,137,4,8,...,1,1,0,0,1,1,0,1,0,1
396,51,70,3,0,110,115,6,134,2,9,...,1,1,0,0,1,1,0,0,0,0
397,51,90,0,0,207,80,6,142,5,8,...,1,1,0,0,1,1,0,1,0,1
398,51,80,0,0,100,49,1,140,5,16,...,1,1,0,0,0,0,0,1,0,0

In [12]:
independent.shape

(399, 27)

In [13]:
dependent=dataset[['classification_yes']]

In [14]:
dependent.shape

(399, 1)

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [16]:
x_train

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
240,60,100,0,3,263,27,1,135,4,12,...,1,1,0,0,1,1,1,1,0,0
218,57,80,0,0,120,48,1,137,4,11,...,1,1,0,0,1,1,0,1,0,0
101,42,70,0,0,75,31,1,141,3,16,...,1,1,0,0,0,0,0,1,0,0
311,66,70,1,0,248,30,1,138,5,12,...,1,1,0,0,1,1,0,1,0,0
194,55,80,0,0,146,57,3,137,4,9,...,1,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
323,68,70,0,0,98,86,4,135,3,9,...,1,1,0,0,1,1,1,0,1,0
192,54,90,1,0,150,18,1,140,4,12,...,1,0,0,0,0,0,0,0,1,1
117,45,80,0,0,107,15,1,141,4,11,...,1,0,0,0,0,0,0,1,0,0
47,30,80,0,0,89,42,0,139,5,16,...,1,1,0,0,0,0,0,1,0,0
172,51,60,0,0,129,25,1,139,5,17,...,1,1,0,0,0,0,0,1,0,0

In [17]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
param_grid={"n_neighbors": [3, 5, 7, 11, 15],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan"]}
grid=GridSearchCV( KNeighborsClassifier(), param_grid, refit=True, verbose=3, n_jobs=-1, scoring="accuracy")
grid.fit(x_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

C:\ANACONDA\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 11, 15],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy', verbose=3)

In [20]:
re=grid.cv_results_

In [21]:
print(re)

{'mean_fit_time': array([0.02325797, 0.01689944, 0.01275573, 0.01904454, 0.01633143,
       0.01507306, 0.00779691, 0.01297908, 0.00640945, 0.00665383,
       0.01066103, 0.00699286, 0.00583687, 0.00604806, 0.00695472,
       0.00724649, 0.01051917, 0.00745201, 0.00818644, 0.00693412]), 'std_fit_time': array([0.01667419, 0.00567876, 0.00587274, 0.01060886, 0.00790033,
       0.00733179, 0.00085339, 0.00262078, 0.0015123 , 0.00232913,
       0.00422385, 0.0007842 , 0.00037004, 0.00083935, 0.00126888,
       0.00201266, 0.00164929, 0.00166515, 0.00136599, 0.00105519]), 'mean_score_time': array([0.05046158, 0.0569325 , 0.02991705, 0.01671686, 0.01855121,
       0.0114779 , 0.01796947, 0.00910687, 0.0145524 , 0.00906525,
       0.05695386, 0.0454875 , 0.02498746, 0.01195984, 0.01341796,
       0.00964842, 0.01371121, 0.00850644, 0.01458406, 0.0088191 ]), 'std_score_time': array([0.00301538, 0.0176225 , 0.00970832, 0.00542294, 0.00227522,
       0.00157777, 0.00362748, 0.00222674, 0.00170215, 0.00140647,
       0.00284333, 0.00187499, 0.01441404, 0.00155646, 0.00262876,
       0.00238086, 0.00135107, 0.00107309, 0.00085523, 0.00043548]), 'param_metric': masked_array(data=['euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'euclidean', 'euclidean',
                   'euclidean', 'euclidean', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan',
                   'manhattan', 'manhattan', 'manhattan', 'manhattan'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'param_n_neighbors': masked_array(data=[3, 3, 5, 5, 7, 7, 11, 11, 15, 15, 3, 3, 5, 5, 7, 7, 11,
                   11, 15, 15],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=999999), 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                   'uniform', 'distance', 'uniform', 'distance',
                   'uniform', 'distance', 'uniform', 'distance',
                   'uniform', 'distance', 'uniform', 'distance',
                   'uniform', 'distance', 'uniform', 'distance'],
             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False],
       fill_value=np.str_('?'),
            dtype=object), 'params': [{'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'uniform'}, {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}, {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'uniform'}, {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'distance'}, {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'uniform'}, {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'distance'}, {'metric': 'euclidean', 'n_neighbors': 11, 'weights': 'uniform'}, {'metric': 'euclidean', 'n_neighbors': 11, 'weights': 'distance'}, {'metric': 'euclidean', 'n_neighbors': 15, 'weights': 'uniform'}, {'metric': 'euclidean', 'n_neighbors': 15, 'weights': 'distance'}, {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'uniform'}, {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'}, {'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'uniform'}, {'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'distance'}, {'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'uniform'}, {'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'distance'}, {'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'uniform'}, {'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'distance'}, {'metric': 'manhattan', 'n_neighbors': 15, 'weights': 'uniform'}, {'metric': 'manhattan', 'n_neighbors': 15, 'weights': 'distance'}], 'split0_test_score': array([0.66666667, 0.7037037 , 0.74074074, 0.7037037 , 0.77777778,
       0.7037037 , 0.83333333, 0.7962963 , 0.81481481, 0.7962963 ,
       0.75925926, 0.75925926, 0.7962963 , 0.77777778, 0.83333333,
       0.81481481, 0.85185185, 0.83333333, 0.83333333, 0.7962963 ]), 'split1_test_score': array([0.73584906, 0.73584906, 0.67924528, 0.67924528, 0.69811321,
       0.67924528, 0.73584906, 0.67924528, 0.77358491, 0.73584906,
       0.73584906, 0.73584906, 0.71698113, 0.71698113, 0.71698113,
       0.71698113, 0.77358491, 0.75471698, 0.77358491, 0.73584906]), 'split2_test_score': array([0.71698113, 0.75471698, 0.66037736, 0.69811321, 0.64150943,
       0.67924528, 0.62264151, 0.66037736, 0.66037736, 0.67924528,
       0.73584906, 0.77358491, 0.64150943, 0.69811321, 0.66037736,
       0.71698113, 0.66037736, 0.69811321, 0.66037736, 0.67924528]), 'split3_test_score': array([0.71698113, 0.75471698, 0.69811321, 0.75471698, 0.71698113,
       0.77358491, 0.69811321, 0.73584906, 0.69811321, 0.73584906,
       0.73584906, 0.77358491, 0.71698113, 0.75471698, 0.71698113,
       0.77358491, 0.73584906, 0.75471698, 0.71698113, 0.73584906]), 'split4_test_score': array([0.73584906, 0.73584906, 0.67924528, 0.73584906, 0.62264151,
       0.71698113, 0.69811321, 0.69811321, 0.69811321, 0.67924528,
       0.75471698, 0.75471698, 0.67924528, 0.73584906, 0.62264151,
       0.71698113, 0.71698113, 0.71698113, 0.67924528, 0.69811321]), 'mean_test_score': array([0.71446541, 0.73696716, 0.69154437, 0.71432565, 0.69140461,
       0.71055206, 0.71761006, 0.71397624, 0.7290007 , 0.725297  ,
       0.74430468, 0.75939902, 0.71020266, 0.73668763, 0.71006289,
       0.74786862, 0.74772886, 0.75157233, 0.7327044 , 0.72907058]), 'std_test_score': array([0.02534521, 0.01864977, 0.0273399 , 0.02720668, 0.05545698,
       0.03470332, 0.06856211, 0.04813674, 0.05651381, 0.04360072,
       0.01045512, 0.013993  , 0.05134419, 0.02789442, 0.07127759,
       0.04001308, 0.06360341, 0.04638765, 0.06345659, 0.04013007]), 'rank_test_score': array([13,  6, 19, 14, 20, 16, 12, 15, 10, 11,  5,  1, 17,  7, 18,  3,  4,
        2,  8,  9], dtype=int32)}

In [22]:
grid_predictions=grid.predict(x_test)

In [23]:
grid_predictions

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0])

In [24]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_predictions)

In [26]:
print(cm)

[[48  3]
 [22 60]]

In [27]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_predictions)

In [29]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.69      0.94      0.79        51
           1       0.95      0.73      0.83        82

    accuracy                           0.81       133
   macro avg       0.82      0.84      0.81       133
weighted avg       0.85      0.81      0.81       133