In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
dataset=pd.read_csv("CKD.csv")

In [5]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [9]:
dataset=pd.get_dummies(dataset,drop_first=True).astype(int)

In [10]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2,76,3,0,148,57,3,137,4,12,...,0,0,0,0,0,0,1,1,0,1
1,3,76,2,0,148,22,0,137,4,10,...,1,0,0,0,0,0,1,0,0,1
2,4,76,1,0,99,23,0,138,4,12,...,1,0,0,0,0,0,1,0,0,1
3,5,76,1,0,148,16,0,138,3,8,...,1,0,0,0,0,0,1,0,1,1
4,5,50,0,0,148,25,0,137,4,11,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51,70,0,0,219,36,1,139,3,12,...,1,0,0,0,0,0,1,0,0,1
395,51,70,0,2,220,68,2,137,4,8,...,1,0,0,1,1,0,1,0,1,1
396,51,70,3,0,110,115,6,134,2,9,...,1,0,0,1,1,0,0,0,0,1
397,51,90,0,0,207,80,6,142,5,8,...,1,0,0,1,1,0,1,0,1,1
398,51,80,0,0,100,49,1,140,5,16,...,1,0,0,0,0,0,1,0,0,0

In [11]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [13]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes',]]

In [8]:
independent

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hrmo,pcv,wc,rc,htn,dm,cad,appet,pe,ane
0,2.000000,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,12.518156,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no
1,3.000000,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,10.700000,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no
2,4.000000,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,12.000000,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no
3,5.000000,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,8.100000,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes
4,5.000000,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,11.800000,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,12.500000,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no
395,51.492308,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,8.700000,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes
396,51.492308,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,9.100000,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no
397,51.492308,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,8.500000,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes
398,51.492308,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,16.300000,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no

In [14]:
dependent=dataset['classification_yes']

In [15]:
dependent

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [18]:
x_test

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,rbc_normal,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes
132,46,70,0,0,100,47,0,142,3,16,...,1,1,0,0,0,0,0,1,0,0
309,66,90,2,0,153,76,3,137,4,12,...,1,1,0,1,0,0,0,0,0,0
334,69,70,0,0,83,42,1,139,3,16,...,1,1,0,0,0,0,0,1,0,0
196,55,100,1,4,297,53,2,139,4,11,...,1,1,0,0,1,1,0,1,0,0
246,60,90,2,0,105,53,2,136,5,11,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349,71,70,0,0,81,18,0,145,5,14,...,1,1,0,0,0,0,0,1,0,0
168,50,80,0,0,137,46,0,139,5,14,...,1,1,0,0,0,0,0,1,0,0
150,48,100,0,0,103,79,5,135,6,6,...,1,1,0,0,1,0,1,0,0,0
392,51,60,3,0,148,34,1,137,4,10,...,0,0,0,0,0,0,0,1,0,0
66,34,60,0,0,91,49,1,135,4,13,...,1,1,0,0,0,0,0,1,0,0

In [20]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

C:\ANACONDA\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=0)

In [21]:
y_pred=classifier.predict(x_test)

In [22]:
y_pred

array([0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0])

In [23]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [24]:
print(cm)

[[46  5]
 [10 72]]

In [25]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,y_pred)

In [26]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.82      0.90      0.86        51
           1       0.94      0.88      0.91        82

    accuracy                           0.89       133
   macro avg       0.88      0.89      0.88       133
weighted avg       0.89      0.89      0.89       133